### ISSUE TITLE
Module doesn't build on Windows

### ISSUE THREAD

**Issue by pmqs** [Altai-man/perl6-Compress-Bzip2-Raw#3]
My module, `Archive::SimpleZip`,  indirectly uses `Compress-Bzip2-Raw`

Don't develop on Windows myself, but created an .`appveyor` file on github to get it tested on Windows. 

This was the result - looks like `fopen` is the culprit.

```
===> Testing: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
Cannot locate symbol 'fopen' in native library ''
  in method setup at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 287
  in method CALL-ME at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 576
  in block <unit> at t\01_sanity.t line 14
===> Testing [FAIL]: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
```

**Comment by Altai-man** [comment]
Hello. `fopen`/`close` pair is exposed to work with handles and this is why it is in the test in question...
Do you know how `Zlib` module handles this problem?

I'll try to investigate it tomorrow.

**Comment by pmqs** [comment]
You don't pass a filehandle to the closest equivalent function in the zlib API. With zlib, you pass the filename and the zlib code opens the file behind the scenes.

`our sub gzopen(Str is encoded('ascii'), Str is encoded('ascii')) returns gzFile is native(&find-lib) is export { * }`

**Comment by Altai-man** [comment]
That's unfortunate.

Technically, we can write a C wrapper that provides a similar function.

I wonder how `fopen` can be called on Windows from NativeCall. Maybe need to read bzip docs about Windows support.

**Comment by pmqs** [comment]
I think the `fopen` function lives in the CRT library on Windows. See [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2019) for the Microsoft documentation.

When I wrote the Perl 5 equivalent of this module I deliberately excluded support for the `bzReadOpen` functions. They didn't add anything useful that I couldn't write in Perl using the low-level compression functions.

**Comment by Altai-man** [comment]
Just added https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/commit/5c2a5c03efcbc0019666682afebda06271efdcfa and now it complains only about bz2.dll being missed on my virtual machine.
Can you please check if it resolves the issue?

**Comment by pmqs** [comment]
I get the same. Below is from https://ci.appveyor.com/project/pmqs/archive-simplezip/builds/25130051

```
===> Testing: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
Cannot locate native library 'bz2.dll': error 0x7e
  in method setup at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 287
  in method CALL-ME at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 576
  in sub bzWriteOpen at C:\Users\appveyor\.zef\store\perl6-Compress-Bzip2-Raw.git\5c2a5c03efcbc0019666682afebda06271efdcfa\lib\Compress\Bzip2\Raw.pm6 (Compress::Bzip2::Raw) line 78
  in block <unit> at t\01_sanity.t line 15
===> Testing [FAIL]: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
```

I'll see if I can convince appveyor to load the bzip2 library.

**Comment by Altai-man** [comment]
Well, previously we had
>Cannot locate symbol 'fopen' in native library ''

and now we have

>Cannot locate native library 'bz2.dll': error 0x7e

Which is a progress. Yes, worth looking into installation of bz2.dll on Windows.

**Comment by pmqs** [comment]
Some progress. 

Created a fork (https://github.com/pmqs/perl6-Compress-Bzip2-Raw) with all the changes noted below. 

I convinced appveyor to install the **bz2.dll** library, by adding this to the `.appveyor.yml` file (which I added to my fork of the module).

```
  - vcpkg install bzip2:x64-windows
  - SET PATH=C:\tools\vcpkg\installed\x64-windows\bin;%PATH%
```
Once I did that I got `close` as an unresolved symbol 

```
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
not ok 1 - Stream was opened.
not ok 2 - No errors in writing.
ok 3 - Stream was closed properly.
# Failed test 'Stream was opened.'
# at t\01_sanity.t line 16
# Failed test 'No errors in writing.'
# at t\01_sanity.t line 21
Cannot locate symbol 'close' in native library 'msvcrt'
  in method setup at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 287
  in method CALL-ME at C:\rakudo\share\perl6\sources\947BDAB9F96E0E5FCCB383124F923A6BF6F8D76B (NativeCall) line 576
  in block <unit> at t\01_sanity.t line 27
===> Testing [FAIL]: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
Command exited with code 1
```

Not sure how this code ever worked using `close`. Surely a file opened with `fopen` needs to use  `fclose` to close it? So changed the code to use `fclose`.

That got me past the unresolved functions (finally), but now the test harness was failing

```
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
not ok 1 - Stream was opened.
# Failed test 'Stream was opened.'
# at t\01_sanity.t line 16
not ok 2 - No errors in writing.
# Failed test 'No errors in writing.'
# at t\01_sanity.t line 21
ok 3 - Stream was closed properly.
not ok 4 - Stream was opened.
# Failed test 'Stream was opened.'
# at t\01_sanity.t line 33
not ok 5 - No errors at reading
# Failed test 'No errors at reading'
# at t\01_sanity.t line 40
not ok 6 - Text is correct.
# Failed test 'Text is correct.'
# at t\01_sanity.t line 43
# expected: 'Text string.'
#      got: ''
ok 7 - Stream was closed properly.
1..7
# Looks like you failed 5 tests of 7
```
Added debug to the first failing test

```
my $handle = fopen("/tmp/test.bz2", "wb");
my $bz = bzWriteOpen($bzerror, $handle);
is $bzerror, BZ_OK, 'Stream was opened.'
  or diag "bzWriteOpen returned $bzerror";
```

That gives more detail on the failing test

```
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
not ok 1 - Stream was opened.
not ok 2 - No errors in writing.
ok 3 - Stream was closed properly.
not ok 4 - Stream was opened.
not ok 5 - No errors at reading
not ok 6 - Text is correct.
ok 7 - Stream was closed properly.
1..7
# Failed test 'Stream was opened.'
# at t\01_sanity.t line 16
# expected: '0'
#      got: '-2'
# bzWriteOpen returned -2
# Failed test 'No errors in writing.'
# at t\01_sanity.t line 22
# Failed test 'Stream was opened.'
# at t\01_sanity.t line 34
# Failed test 'No errors at reading'
# at t\01_sanity.t line 41
# Failed test 'Text is correct.'
# at t\01_sanity.t line 44
# expected: 'Text string.'
#      got: ''
# Looks like you failed 5 tests of 7
```
The -2 error is `BZ_PARAM_ERROR`. Below is from the `bzWriteOpen` section in the bzip2 man page
```
   BZFILE *bzWriteOpen ( int *bzerror, FILE *f, 
                         int blockSize100k, int verbosity,
                         int workFactor );
      ...
      BZ_PARAM_ERROR 
         if f is NULL 
         or blockSize100k < 1 or blockSize100k > 9
```

`bzWriteOpen` takes 5 parameters but the test in `01_sanity.t` is only giving it 2. 

`my $bz = bzWriteOpen($bzerror, $handle);
` 

The important one to have a non-zero value is `blockSize100k` so I added more parameters

`my $bz = bzWriteOpen($bzerror, $handle, 1, 0, 0);
`

Also - just noticed that the output file being created is to `**/tmp**`. That won't exist on Windows, so I'm writing the file into  `$*TEMPDIR`.

Still not quite there - looks like the test harness is terminating early.

```
Testing with plugin: Zef::Service::Shell::Test+{<anon|1>}
# Filename is 'C:\Users\appveyor\AppData\Local\Temp\1/test.bz2'
ok 1 - Stream was opened.
ok 2 - No errors in writing.
===> Testing [FAIL]: Compress::Bzip2::Raw:ver<0.2.0>:auth<github:Altai-man>
Command exited with code 1
```

**Comment by Altai-man** [comment]
This sounds not very nice. I guess, after a couple of years this module requires a de-bitrot session.

Thanks for all the efforts, I'll try to make it working.

**Comment by Altai-man** [comment]
>bzWriteOpen takes 5 parameters but the test in 01_sanity.t is only giving it 2.

It is because we have another candidate, which takes only 2 arguments and passes default values for the rest, see https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/blob/master/lib/Compress/Bzip2/Raw.pm6#L77

**Comment by Altai-man** [comment]
Can you please make a PR with your appveyor config?

**Comment by pmqs** [comment]
sent PR with my changes - see https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/pull/4

**Comment by Altai-man** [comment]
Merged the PR, let's see if I can make it work.
The commit history is a bit messy, please, in future try to keep it cleaner either rebasing or committing complete changes.

**Comment by pmqs** [comment]
Sorry about the PR. Still coming up the learning curve with git I'm afraid.

Shout if you need a hand with anything.

**Comment by Altai-man** [comment]
No worries, nothing too bad happened.

>Shout if you need a hand with anything

Sure, thanks for your attention and efforts.

Right now appveynor just stops without any sensible message after https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/blob/debug-branch/t/01_sanity.t#L28
This is... just odd.

**Comment by pmqs** [comment]
Yep. That matches what I got as well. Very strange.

**Comment by pmqs** [comment]
I managed to get Perl6 running on a Windows debugger and found out where the test harness is failing.

The Perl6 code calls `BZ2_bzWriteClose` which then calls `BZ2_bzWriteClose64` (in bzlib.c). That finalises the compressed data and calls `fwrite` to write the compressed data to disk. In the VS windows debugger I see the code calling `fwrite`, but it never comes back -- the debugger just hangs forever. This is the first time the code attempts to use `fwrite`.

![image](https://user-images.githubusercontent.com/2691108/59389649-b7b84c00-8d66-11e9-9b9b-e3b33f7187ed.png)

Perhaps something is wrong with the  bzip2 dll that vcpkg has installed?  Then I noticed that vcpkg installs the command-line version of bzip2 as well as the dll. That works fine and under the hood it also uses `BZ2_bzWriteClose`. That suggests that the bzip2 library code is ok, but there is an issue with how it is  linked with Perl6.

**Comment by Altai-man** [comment]
Sorry for the delay with responding.

Thanks a lot for your investigation, yet I am not sure I am qualified enough to debug NativeCall (or, rather, I am not qualified at all).

I think we can permanently or temporarily unbreak the Windows build by simply not exporting file IO on Windows, leaving only the buffer one.

This case also wants a bug report for rakudo.

**Comment by Altai-man** [comment]
If your module can go with file IO not being exported on Windows, I'll gladly write a patch to do it.

**Comment by pmqs** [comment]
My code doesn't use any of the file IO from `Compress-Bzip2-Raw`, but it  uses `Compress-Bzip2-Raw` via `Compress-Bzip2`. I see that `Compress-Bzip2` uses `bzWriteClose`, so there will be an issue there as well.  You would have to (somehow) patch two modules to not use file IO on Windows if you want to go down that path. Might be easier to just create non-IO variants of both modules.

Better would be to fix the Windows issue, but like you, I'm not qualified to debug Nativecall, especially on Windows.

Agree that this need passed on to rakudo. Was going to put a toy module together that just exported nativecall to the `fopen`/`fwrite`/`fclose `functions to see if that worked. Would make for a better bug report if it turns out it doesn't work on Windows either.

If you don't feel like patching, lets see how the report to rakudo goes. 

I can create the rakudo bug, if you like?

**Comment by Altai-man** [comment]
>If you don't feel like patching

As my understanding goes, your module is blocked by this one, at least on Windows. If it is an issue, we surely should workaround it using `EXPORT` sub. Currently Rakudo has a lot of tickets and the Windows issues are not so fun to deal with, so it is unpredictable how soon the fix will be ready.
Considering this, I guess I'll look at writing a patch this evening.

>Was going to put a toy module together that just exported nativecall to the fopen/fwrite/fclose functions to see if that worked. Would make for a better bug report if it turns out it doesn't work on Windows either.

This will be truly helpful.

>I can create the rakudo bug, if you like?

Sure, feel welcomed to do so.

**Comment by Altai-man** [comment]
Started to get it in shape, though there are still tests to write for both Linux and Windows boxed.

**Comment by pmqs** [comment]
See https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/pull/5 for a fix

**Comment by Altai-man** [comment]
Closing as #5 is merged, please re-open if needed. Thanks for such a massive contribution!
